# Generated by Django 2.2.7 on 2021-05-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.TextField()),
            ],
            options={
                'db_table': 'CLIENTES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.TextField()),
                ('SUGESTED_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MULTIPLIER', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'PRODUTOS',
                'managed': True,
            },
        ),
    ]
