# Generated by Django 2.2.7 on 2021-05-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Clients')),
            ],
        ),
    ]
