# Generated by Django 2.2.7 on 2021-05-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='orders',
            table='PEDIDOS',
        ),
    ]
