# Generated by Django 2.2.7 on 2021-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20210528_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='PRODUCTS',
            field=models.ManyToManyField(to='pedidos.Products'),
        ),
    ]
