# Generated by Django 2.2.7 on 2021-05-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_orders_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PEDIDOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTITY', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.TextField()),
                ('SUGESTED_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MULTIPLIER', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'PRODUTOS',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='CLIENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Client'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='ORDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Order'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='PRODUCTS',
            field=models.ManyToManyField(through='pedidos.OrderDetails', to='pedidos.Product'),
        ),
    ]
