# Generated by Django 2.2.7 on 2021-05-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20210529_1129'),
    ]

    operations = [
    ]
