# Generated by Django 2.2.7 on 2021-05-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20210529_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='PRODUCTS',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='CLIENT',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='ORDER',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='PRODUCT',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
