# Generated by Django 2.2.7 on 2021-05-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0011_auto_20210529_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CLIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Client')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.TextField()),
                ('SUGESTED_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MULTIPLIER', models.PositiveIntegerField(default=1)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTITY', models.PositiveIntegerField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Order')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='PRODUCTS',
            field=models.ManyToManyField(through='pedidos.OrderDetails', to='pedidos.Product'),
        ),
    ]
