# Generated by Django 3.0.6 on 2020-06-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_en',
            name='description',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
